package at.ac.tuwien.sepr.groupphase.backend.repository;

import at.ac.tuwien.sepr.groupphase.backend.entity.*;
import at.ac.tuwien.sepr.groupphase.backend.type.UserRole;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;

import java.time.LocalDateTime;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests for EventRepository CUSTOM @Query methods only.
 * Standard Spring Data methods are not tested (auto-generated by Spring).
 */
@DataJpaTest
class EventRepositoryTest {

    @Autowired
    private TestEntityManager entityManager;

    @Autowired
    private EventRepository eventRepository;

    private Location location;
    private Artist artist;
    private Event eventConcert;
    private Event eventOpera;
    private User user;

    @BeforeEach
    void setUp() {
        location = new Location();
        location.setName("Wiener Stadthalle");
        location.setStreet("Roland-Rainer-Platz");
        location.setStreetNumber("1");
        location.setCity("Wien");
        location.setZipCode(1150);
        location.setStagePosition("TOP");
        entityManager.persist(location);

        Sector sector = new Sector();
        sector.setName("Main Hall");
        sector.setLocation(location);
        entityManager.persist(sector);

        PriceCategory priceCategory = new PriceCategory();
        priceCategory.setDescription("Standard");
        priceCategory.setBasePrice(5000);
        priceCategory.setSector(sector);
        entityManager.persist(priceCategory);

        Seat seat = new Seat();
        seat.setRowNumber(1);
        seat.setSeatNumber(1);
        seat.setSector(sector);
        seat.setPriceCategory(priceCategory);
        entityManager.persist(seat);

        artist = new Artist();
        artist.setName("Die Ärzte");
        artist.setIsBand(true);
        entityManager.persist(artist);

        eventConcert = new Event();
        eventConcert.setTitle("Rock Concert");
        eventConcert.setType("CONCERT");
        eventConcert.setDescription("Amazing rock concert");
        eventConcert.setDurationMinutes(120);
        eventConcert.setDateTime(LocalDateTime.of(2026, 6, 15, 20, 0));
        eventConcert.setLocation(location);
        eventConcert.setArtists(List.of(artist));
        entityManager.persist(eventConcert);

        eventOpera = new Event();
        eventOpera.setTitle("La Traviata");
        eventOpera.setType("OPERA");
        eventOpera.setDescription("Classic opera performance");
        eventOpera.setDurationMinutes(180);
        eventOpera.setDateTime(LocalDateTime.of(2026, 7, 20, 19, 0));
        eventOpera.setLocation(location);
        entityManager.persist(eventOpera);

        user = new User();
        user.setEmail("test@example.com");
        user.setPasswordHash("$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy");
        user.setUserRole(UserRole.ROLE_USER);
        user.setFirstName("Test");
        user.setLastName("User");
        user.setAddress("Test Street 1");
        entityManager.persist(user);

        entityManager.flush();
    }

    @Test
    void findByDurationBetween_findsEventsInRange() {
        List<Event> results = eventRepository.findByDurationBetween(100, 150);

        assertThat(results).hasSize(1);
        assertThat(results.get(0).getDurationMinutes()).isEqualTo(120);
    }

    @Test
    void findByDurationBetween_findsMultipleEvents() {
        List<Event> results = eventRepository.findByDurationBetween(100, 200);

        assertThat(results).hasSize(2);
    }

    @Test
    void searchEvents_searchesAcrossMultipleFields() {
        List<Event> results = eventRepository.searchEvents("classic");

        assertThat(results).hasSize(1);
        assertThat(results.get(0).getDescription()).contains("Classic");
    }

    @Test
    void searchEvents_searchesTitleField() {
        List<Event> results = eventRepository.searchEvents("traviata");

        assertThat(results).hasSize(1);
        assertThat(results.get(0).getTitle()).isEqualTo("La Traviata");
    }

    @Test
    void searchEvents_searchesTypeField() {
        List<Event> results = eventRepository.searchEvents("concert");

        assertThat(results).hasSize(1);
        assertThat(results.get(0).getType()).isEqualTo("CONCERT");
    }

    @Test
    void findByArtistId_findsEventsByArtist() {
        List<Event> results = eventRepository.findByArtistId(artist.getId());

        assertThat(results).hasSize(1);
        assertThat(results.get(0).getArtists()).contains(artist);
    }

    @Test
    void findByArtistId_returnsEmptyForUnusedArtist() {
        Artist unused = new Artist();
        unused.setName("Unused");
        unused.setIsBand(false);
        entityManager.persist(unused);
        entityManager.flush();

        List<Event> results = eventRepository.findByArtistId(unused.getId());

        assertThat(results).isEmpty();
    }

    @Test
    void searchEventsByCriteria_combinesMultipleCriteria() {
        List<Event> results = eventRepository.searchEventsByCriteria(
            "concert", "CONCERT", 100, 150, null, null, location.getId()
        );

        assertThat(results).hasSize(1);
        assertThat(results.get(0).getTitle()).isEqualTo("Rock Concert");
    }

    @Test
    void searchEventsByCriteria_allNullReturnsAll() {
        List<Event> results = eventRepository.searchEventsByCriteria(
            null, null, null, null, null, null, null
        );

        assertThat(results).hasSize(2);
    }

    @Test
    void searchEventsByCriteria_filtersByDateRange() {
        LocalDateTime start = LocalDateTime.of(2026, 7, 1, 0, 0);
        LocalDateTime end = LocalDateTime.of(2026, 7, 31, 23, 59);

        List<Event> results = eventRepository.searchEventsByCriteria(
            null, null, null, null, start, end, null
        );

        assertThat(results).hasSize(1);
        assertThat(results.get(0).getTitle()).isEqualTo("La Traviata");
    }

    @Test
    void searchEventsByTimeAndPrice_findsByPriceRange() {
        List<Event> results = eventRepository.searchEventsByTimeAndPrice(
            null, null, 4000, 6000, null
        );

        assertThat(results).hasSize(2);
    }

    @Test
    void searchEventsByTimeAndPrice_combinesDateAndPrice() {
        LocalDateTime start = LocalDateTime.of(2026, 6, 1, 0, 0);
        LocalDateTime end = LocalDateTime.of(2026, 6, 30, 23, 59);

        List<Event> results = eventRepository.searchEventsByTimeAndPrice(
            start, end, 4000, 6000, null
        );

        assertThat(results).hasSize(1);
    }

    @Test
    void searchEventsByTimeAndPrice_noPriceMatch() {
        List<Event> results = eventRepository.searchEventsByTimeAndPrice(
            null, null, 10000, 20000, null
        );

        assertThat(results).isEmpty();
    }
}